package tn.esprit.spring.procedureservice.surgical.service;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;
import org.springframework.stereotype.Service;
import tn.esprit.spring.procedureservice.surgical.domain.entity.CareTask;
import tn.esprit.spring.procedureservice.surgical.domain.entity.Complication;
import tn.esprit.spring.procedureservice.surgical.domain.entity.PostOpObservation;
import tn.esprit.spring.procedureservice.surgical.domain.entity.PreOpAssessment;
import tn.esprit.spring.procedureservice.surgical.domain.entity.SurgicalCase;
import tn.esprit.spring.procedureservice.surgical.repository.CareTaskRepository;
import tn.esprit.spring.procedureservice.surgical.repository.ComplicationRepository;
import tn.esprit.spring.procedureservice.surgical.repository.PostOpObservationRepository;
import tn.esprit.spring.procedureservice.surgical.repository.PreOpAssessmentRepository;

@Service
public class SurgicalCasePdfService {
    private static final Font TITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.BLACK);
    private static final Font SECTION_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.BLACK);
    private static final Font BODY_FONT = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.BLACK);
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final DateTimeFormatter TIME_FORMAT = DateTimeFormatter.ofPattern("HH:mm");

    private final SurgicalCaseService surgicalCaseService;
    private final PreOpAssessmentRepository preOpAssessmentRepository;
    private final PostOpObservationRepository postOpObservationRepository;
    private final ComplicationRepository complicationRepository;
    private final CareTaskRepository careTaskRepository;

    public SurgicalCasePdfService(
        SurgicalCaseService surgicalCaseService,
        PreOpAssessmentRepository preOpAssessmentRepository,
        PostOpObservationRepository postOpObservationRepository,
        ComplicationRepository complicationRepository,
        CareTaskRepository careTaskRepository
    ) {
        this.surgicalCaseService = surgicalCaseService;
        this.preOpAssessmentRepository = preOpAssessmentRepository;
        this.postOpObservationRepository = postOpObservationRepository;
        this.complicationRepository = complicationRepository;
        this.careTaskRepository = careTaskRepository;
    }

    public byte[] generateCaseSummaryPdf(Long surgicalCaseId) {
        SurgicalCase surgicalCase = surgicalCaseService.getById(surgicalCaseId);
        Optional<PreOpAssessment> latestPreOp = preOpAssessmentRepository.findTopBySurgicalCaseIdOrderByIdDesc(surgicalCaseId);
        List<PostOpObservation> postOpObservations = postOpObservationRepository.findBySurgicalCaseIdOrderByIdDesc(surgicalCaseId);
        List<Complication> complications = complicationRepository.findBySurgicalCaseIdOrderByIdDesc(surgicalCaseId);
        List<CareTask> careTasks = careTaskRepository.findBySurgicalCaseIdOrderByIdAsc(surgicalCaseId);

        ByteArrayOutputStream output = new ByteArrayOutputStream();
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, output);
            document.open();

            addTitle(document, surgicalCase);
            addSummaryTable(document, surgicalCase);
            addSection(document, "Operational Snapshot");
            addParagraph(document, workflowSummary(surgicalCase));
            addSection(document, "Latest Pre-Op Assessment");
            addParagraph(document, latestPreOp.map(PreOpAssessment::getNotes).orElse("No pre-op assessment recorded."));
            addSection(document, "Post-Op Observations");
            addBulletList(document, postOpObservations.stream().map(PostOpObservation::getNotes).toList(), "No post-op observation recorded.");
            addSection(document, "Complications");
            addBulletList(document, complications.stream().map(Complication::getDescription).toList(), "No complications recorded.");
            addSection(document, "Care Tasks");
            addBulletList(document, careTasks.stream().map(this::formatTask).toList(), "No care tasks assigned.");

            document.add(new Paragraph(" "));
            addParagraph(document, "Generated by procedure-service surgical management module.");
        } catch (DocumentException ex) {
            throw new IllegalStateException("Failed to generate surgical case PDF.", ex);
        } finally {
            document.close();
        }

        return output.toByteArray();
    }

    private void addTitle(Document document, SurgicalCase surgicalCase) throws DocumentException {
        String patientName = safe(surgicalCase.getFirstName()) + " " + safe(surgicalCase.getLastName());
        document.add(new Paragraph("Surgical Case Summary", TITLE_FONT));
        document.add(new Paragraph(patientName.trim().isBlank() ? "Patient file" : patientName.trim(), SECTION_FONT));
        document.add(new Paragraph(" "));
    }

    private void addSummaryTable(Document document, SurgicalCase surgicalCase) throws DocumentException {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setSpacingAfter(12f);

        addRow(table, "Patient ID", surgicalCase.getPatientId());
        addRow(table, "Medical Record Number", surgicalCase.getMedicalRecordNumber());
        addRow(table, "Age / Gender", safe(surgicalCase.getAge()) + " years / " + safe(surgicalCase.getGender()));
        addRow(table, "Surgery Type", surgicalCase.getSurgeryType());
        addRow(table, "Procedure Name", surgicalCase.getProcedureName());
        addRow(table, "Category", safe(surgicalCase.getSurgeryCategory()));
        addRow(table, "Urgency", safe(surgicalCase.getUrgencyLevel()));
        addRow(table, "Lead Surgeon", surgicalCase.getSurgeonId());
        addRow(table, "Assistant Surgeon", safe(surgicalCase.getAssistantSurgeonId()));
        addRow(table, "Anesthesiologist", safe(surgicalCase.getAnesthesiologistId()));
        addRow(table, "Nurse Team", safe(surgicalCase.getNurseTeam()));
        addRow(table, "Planned Date", surgicalCase.getScheduledDate() != null ? surgicalCase.getScheduledDate().format(DATE_FORMAT) : "-");
        addRow(table, "Planned Time", surgicalCase.getScheduledStartTime() != null ? surgicalCase.getScheduledStartTime().format(TIME_FORMAT) : "-");
        addRow(table, "Estimated Duration", surgicalCase.getEstimatedDurationMinutes() != null ? surgicalCase.getEstimatedDurationMinutes() + " minutes" : "-");
        addRow(table, "Operating Room", safe(surgicalCase.getOperatingRoom()));
        addRow(table, "Case Status", safe(surgicalCase.getStatus()));
        addRow(table, "Offer Status", safe(surgicalCase.getOfferStatus()));

        document.add(table);
    }

    private void addRow(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, SECTION_FONT));
        labelCell.setBackgroundColor(new Color(238, 243, 250));
        labelCell.setPadding(6f);
        table.addCell(labelCell);

        PdfPCell valueCell = new PdfPCell(new Phrase(value == null || value.isBlank() ? "-" : value, BODY_FONT));
        valueCell.setPadding(6f);
        table.addCell(valueCell);
    }

    private void addSection(Document document, String title) throws DocumentException {
        document.add(new Paragraph(title, SECTION_FONT));
        document.add(new Paragraph(" "));
    }

    private void addParagraph(Document document, String value) throws DocumentException {
        document.add(new Paragraph(value == null || value.isBlank() ? "-" : value, BODY_FONT));
        document.add(new Paragraph(" "));
    }

    private void addBulletList(Document document, List<String> items, String emptyMessage) throws DocumentException {
        if (items == null || items.isEmpty()) {
            addParagraph(document, emptyMessage);
            return;
        }

        for (String item : items) {
            document.add(new Paragraph("- " + (item == null || item.isBlank() ? "-" : item), BODY_FONT));
        }
        document.add(new Paragraph(" "));
    }

    private String formatTask(CareTask task) {
        return (task.isDone() ? "[Done] " : "[Pending] ") + safe(task.getTitle());
    }

    private String workflowSummary(SurgicalCase surgicalCase) {
        return "Current status: " + safe(surgicalCase.getStatus())
            + " | Next planning target: " + (surgicalCase.getScheduledDate() != null ? surgicalCase.getScheduledDate().format(DATE_FORMAT) : "-")
            + " " + (surgicalCase.getScheduledStartTime() != null ? surgicalCase.getScheduledStartTime().format(TIME_FORMAT) : "-");
    }

    private String safe(Object value) {
        return value == null ? "-" : String.valueOf(value);
    }
}
