ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE supply_orders ADD COLUMN IF NOT EXISTS expected_delivery_date DATE;
ALTER TABLE supply_orders ADD COLUMN IF NOT EXISTS notes TEXT;
