ALTER TABLE surgical_cases
    ADD COLUMN age INTEGER,
    ADD COLUMN gender VARCHAR(50),
    ADD COLUMN medical_record_number VARCHAR(255),
    ADD COLUMN surgery_type VARCHAR(255),
    ADD COLUMN procedure_name VARCHAR(255),
    ADD COLUMN surgery_category VARCHAR(100),
    ADD COLUMN urgency_level VARCHAR(100),
    ADD COLUMN surgeon_id VARCHAR(255),
    ADD COLUMN assistant_surgeon_id VARCHAR(255),
    ADD COLUMN anesthesiologist_id VARCHAR(255),
    ADD COLUMN nurse_team VARCHAR(255),
    ADD COLUMN scheduled_date DATE,
    ADD COLUMN scheduled_start_time TIME,
    ADD COLUMN estimated_duration_minutes INTEGER,
    ADD COLUMN operating_room VARCHAR(100);
