spring:
  application:
    name: pharmacy-service
  config:
    import: optional:configserver:http://localhost:8888

internal:
  api-key: my-super-secret-internal-key

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
