services:
  keycloak-db:
    image: postgres:16
    container_name: nephro-keycloak-db
    profiles: ["local-keycloak-db"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
    volumes:
      - keycloak_db:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:24.0
    container_name: nephro-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ep-cool-breeze-agqhhjlc.c-2.eu-central-1.aws.neon.tech:5432/KeyCloak?sslmode=require&channel_binding=require
      KC_DB_USERNAME: neondb_owner
      KC_DB_PASSWORD: npg_Zb1Kda5LPlin

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123

      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./realm:/opt/keycloak/data/import

volumes:
  keycloak_db:
