package tn.esprit.spring.procedureservice.dialysis.service;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;
import org.springframework.stereotype.Service;
import tn.esprit.spring.procedureservice.dialysis.domain.entity.DialysisPlan;
import tn.esprit.spring.procedureservice.dialysis.domain.entity.DialysisSession;
import tn.esprit.spring.procedureservice.dialysis.repository.DialysisSessionRepository;

@Service
public class DialysisPlanPdfService {
    private static final Font TITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.BLACK);
    private static final Font SECTION_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.BLACK);
    private static final Font BODY_FONT = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.BLACK);
    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final DateTimeFormatter DATE_TIME_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    private final DialysisPlanService dialysisPlanService;
    private final DialysisSessionRepository dialysisSessionRepository;

    public DialysisPlanPdfService(
        DialysisPlanService dialysisPlanService,
        DialysisSessionRepository dialysisSessionRepository
    ) {
        this.dialysisPlanService = dialysisPlanService;
        this.dialysisSessionRepository = dialysisSessionRepository;
    }

    public byte[] generatePlanSummaryPdf(Long planId) {
        DialysisPlan plan = dialysisPlanService.getById(planId);
        List<DialysisSession> sessions = dialysisSessionRepository.findByPlanIdOrderBySessionDateAsc(planId);

        ByteArrayOutputStream output = new ByteArrayOutputStream();
        Document document = new Document();

        try {
            PdfWriter.getInstance(document, output);
            document.open();

            addTitle(document, plan);
            addSummaryTable(document, plan);
            addSection(document, "Clinical Schedule");
            addParagraph(document, buildScheduleSummary(plan));
            addSection(document, "Generated Sessions");
            addBulletList(document, sessions.stream().map(this::formatSession).toList(), "No sessions generated yet.");
            addSection(document, "Operational Footprint");
            addParagraph(document, buildOperationalFootprint(plan));
            addParagraph(document, "Generated by procedure-service dialysis management module.");
        } catch (DocumentException ex) {
            throw new IllegalStateException("Failed to generate dialysis plan PDF.", ex);
        } finally {
            document.close();
        }

        return output.toByteArray();
    }

    private void addTitle(Document document, DialysisPlan plan) throws DocumentException {
        String patientName = (safe(plan.getFirstName()) + " " + safe(plan.getLastName())).trim();
        document.add(new Paragraph("Dialysis Plan Summary", TITLE_FONT));
        document.add(new Paragraph(patientName.isBlank() ? "Patient plan" : patientName, SECTION_FONT));
        document.add(new Paragraph(" "));
    }

    private void addSummaryTable(Document document, DialysisPlan plan) throws DocumentException {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setSpacingAfter(12f);

        addRow(table, "Patient ID", plan.getPatientId());
        addRow(table, "Patient Name", ((safe(plan.getFirstName()) + " " + safe(plan.getLastName())).trim()));
        addRow(table, "Assigned Nephrologist", plan.getDoctorId());
        addRow(table, "Dialysis Type", plan.getDialysisType());
        addRow(table, "Sessions Per Week", safe(plan.getSessionsPerWeek()));
        addRow(table, "Session Duration", plan.getSessionDurationMinutes() != null ? plan.getSessionDurationMinutes() + " minutes" : "-");
        addRow(table, "Start Date", plan.getStartDate() != null ? plan.getStartDate().format(DATE_FORMAT) : "-");
        addRow(table, "End Date", plan.getEndDate() != null ? plan.getEndDate().format(DATE_FORMAT) : "-");
        addRow(table, "Days of Week", plan.getDaysOfWeek());
        addRow(table, "Blood Flow Rate", plan.getBloodFlowRate() != null ? plan.getBloodFlowRate() + " mL/min" : "-");
        addRow(table, "Dialysate Flow Rate", plan.getDialysateFlowRate() != null ? plan.getDialysateFlowRate() + " mL/min" : "-");
        addRow(table, "Ultrafiltration Goal", plan.getUltrafiltrationGoal() != null ? plan.getUltrafiltrationGoal() + " mL" : "-");
        addRow(table, "Dialysis Center", plan.getDialysisCenterId());
        addRow(table, "Room Number", plan.getRoomNumber());
        addRow(table, "Machine ID", plan.getMachineId());
        addRow(table, "Plan Status", plan.getStatus());

        document.add(table);
    }

    private void addRow(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, SECTION_FONT));
        labelCell.setBackgroundColor(new Color(238, 243, 250));
        labelCell.setPadding(6f);
        table.addCell(labelCell);

        PdfPCell valueCell = new PdfPCell(new Phrase(value == null || value.isBlank() ? "-" : value, BODY_FONT));
        valueCell.setPadding(6f);
        table.addCell(valueCell);
    }

    private void addSection(Document document, String title) throws DocumentException {
        document.add(new Paragraph(title, SECTION_FONT));
        document.add(new Paragraph(" "));
    }

    private void addParagraph(Document document, String value) throws DocumentException {
        document.add(new Paragraph(value == null || value.isBlank() ? "-" : value, BODY_FONT));
        document.add(new Paragraph(" "));
    }

    private void addBulletList(Document document, List<String> items, String emptyMessage) throws DocumentException {
        if (items == null || items.isEmpty()) {
            addParagraph(document, emptyMessage);
            return;
        }

        for (String item : items) {
            document.add(new Paragraph("- " + (item == null || item.isBlank() ? "-" : item), BODY_FONT));
        }
        document.add(new Paragraph(" "));
    }

    private String buildScheduleSummary(DialysisPlan plan) {
        return "Plan status: " + safe(plan.getStatus())
            + " | Frequency: " + safe(plan.getSessionsPerWeek()) + " sessions/week"
            + " | Planned days: " + safe(plan.getDaysOfWeek());
    }

    private String buildOperationalFootprint(DialysisPlan plan) {
        return "Center: " + safe(plan.getDialysisCenterId())
            + " | Room: " + safe(plan.getRoomNumber())
            + " | Machine: " + safe(plan.getMachineId());
    }

    private String formatSession(DialysisSession session) {
        String sessionDate = session.getSessionDate() != null ? session.getSessionDate().format(DATE_TIME_FORMAT) : "-";
        String notes = session.getNotes();
        return sessionDate + " | Notes: " + (notes == null || notes.isBlank() ? "-" : notes);
    }

    private String safe(Object value) {
        return value == null ? "-" : String.valueOf(value);
    }
}
